//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Denomination", Namespace="http://schemas.datacontract.org/2004/07/AtmModel")]
    public partial class Denomination : object
    {
        
        private double DenominationValueField;
        
        private int QuantityField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DenominationValue
        {
            get
            {
                return this.DenominationValueField;
            }
            set
            {
                this.DenominationValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtmService.IAtmService")]
    public interface IAtmService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmService/ProcessWithdrawal", ReplyAction="http://tempuri.org/IAtmService/ProcessWithdrawalResponse")]
        System.Threading.Tasks.Task<AtmService.Denomination[]> ProcessWithdrawalAsync(double requireAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtmService/GetDenominationValue", ReplyAction="http://tempuri.org/IAtmService/GetDenominationValueResponse")]
        System.Threading.Tasks.Task<AtmService.Denomination[]> GetDenominationValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IAtmServiceChannel : AtmService.IAtmService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class AtmServiceClient : System.ServiceModel.ClientBase<AtmService.IAtmService>, AtmService.IAtmService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AtmServiceClient() : 
                base(AtmServiceClient.GetDefaultBinding(), AtmServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAtmService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AtmServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AtmServiceClient.GetBindingForEndpoint(endpointConfiguration), AtmServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AtmServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AtmServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AtmServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AtmServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AtmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AtmService.Denomination[]> ProcessWithdrawalAsync(double requireAmount)
        {
            return base.Channel.ProcessWithdrawalAsync(requireAmount);
        }
        
        public System.Threading.Tasks.Task<AtmService.Denomination[]> GetDenominationValueAsync()
        {
            return base.Channel.GetDenominationValueAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAtmService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAtmService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53199/AtmService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AtmServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAtmService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AtmServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAtmService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAtmService,
        }
    }
}
